const day1 = @import("day1.zig");
const day2 = @import("day2.zig");
const day3 = @import("day3.zig");
const day4 = @import("day4.zig");
const day5 = @import("day5.zig");
const day6 = @import("day6.zig");
const day7 = @import("day7.zig");
const day8 = @import("day8.zig");
const day9 = @import("day9.zig");
const day10 = @import("day10.zig");
const day11 = @import("day11.zig");
const day12 = @import("day12.zig");
const day13 = @import("day13.zig");
const day14 = @import("day14.zig");
const day15 = @import("day15.zig");
const day16 = @import("day16.zig");
const day17 = @import("day17.zig");
const day18 = @import("day18.zig");
const day19 = @import("day19.zig");
const day20 = @import("day20.zig");
const day21 = @import("day21.zig");
const day22 = @import("day22.zig");
const day23 = @import("day23.zig");
const day24 = @import("day24.zig");
const day25 = @import("day25.zig");

pub fn main() !void {
    // try day1.solvePartOne();
    // try day1.solvePartTwo();
    // try day2.solvePartOne();
    // try day2.solvePartTwo();
    // try day3.solvePartOne();
    // try day3.solvePartTwo();
    // try day4.solvePartOne();
    // try day5.solvePartOne();
    // try day5.solvePartTwo();
    // try day6.solvePartOne();
    // try day6.solvePartTwo();
    // try day7.solvePartOne();
    // try day7.solvePartTwo();
    // try day8.solvePartOne();
    // try day8.solvePartTwo();
    // try day9.solvePartOne();
    // try day9.solvePartTwo();
    // try day10.solvePartOne();
    // try day10.solvePartTwo();
    // try day11.solvePartOne();
    // try day11.solvePartTwo();
    // try day12.solvePartOne();
    // try day12.solvePartTwo();
    // try day13.solvePartOne();
    // try day13.solvePartTwo();
    // try day14.solvePartOne();
    // try day14.solvePartTwo();
    // try day15.solvePartOne();
    // try day15.solvePartTwo();
    // try day16.solvePartOne();
    // try day16.solvePartTwo();
    // try day17.solvePartOne();
    // try day17.solvePartTwo();
    // try day18.solvePartOne();
    // try day18.solvePartTwo();
    // try day19.solvePartOne();
    // try day19.solvePartTwo();
    // try day20.solvePartOne();
    // try day20.solvePartTwo();
    // try day21.solvePartOne();
    // try day21.solvePartTwo();
    // try day22.solvePartOne();
    // try day22.solvePartTwo();
    // try day23.solvePartOne();
    // try day23.solvePartTwo();
    // try day24.solvePartOne();
    // try day24.solvePartTwo();
    // try day25.solvePartOne();
    // try day25.solvePartTwo();
}
